<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');

$filter = isset($_GET['search']) ? strtolower($_GET['search']) : null;
$format = isset($_GET['format']) ? strtolower($_GET['format']) : null;

if (!$filter) {
    echo json_encode(['error' => 'Search parameter not provided']);
    exit();
}

$data = [
    ["name" => "Perry Washington", "email" => "Fusce@accumsan.com", "company" => "Tarma"],
    ["name" => "Curran Harding", "email" => "Duis@Mauris.net", "company" => "Crotta d'Adda"],
    ["name" => "Darius Hayes", "email" => "diam.Pellentesque@Nunc.edu", "company" => "Starodub"],
    ["name" => "Jayme Pacheco", "email" => "sagittis@sit.ca", "company" => "Koninksem"],
    ["name" => "Nissim Chang", "email" => "ac@ipsumdolor.net", "company" => "Piedras Negras"],
    ["name" => "Bruce Mcclain", "email" => "laoreet.posuere@Nullatempor.co.uk", "company" => "Nijkerk"],
    ["name" => "Cailin Jones", "email" => "ultrices@orciluctus.edu", "company" => "Fino Mornasco"],
    ["name" => "Madeson Callahan", "email" => "mi.felis.adipiscing@urna.edu", "company" => "Minderhout"],
    ["name" => "Charity Horton", "email" => "Aliquam.ornare.libero@Crasdolor.net", "company" => "Hualañé"],
    ["name" => "Tatyana Galloway", "email" => "lacus.Cras@dolorFusce.co.uk", "company" => "Augusta"],
    ["name" => "Savannah Moore", "email" => "arcu.Morbi.sit@semmollisdui.edu", "company" => "Presles"],
    ["name" => "India Carroll", "email" => "pede.ac@Nullamnisl.com", "company" => "Envigado"],
    ["name" => "Iola Stuart", "email" => "Nullam.feugiat.placerat@parturient.org", "company" => "Roux-Miroir"],
    ["name" => "Hilda Lucas", "email" => "tincidunt@semper.com", "company" => "Ogbomosho"],
    ["name" => "Yoshi Frost", "email" => "felis@dui.com", "company" => "Ruoti"],
    ["name" => "Diana Savage", "email" => "arcu.Sed.et@lectusNullam.net", "company" => "Lacombe"],
    ["name" => "Lester Jennings", "email" => "vitae@facilisis.ca", "company" => "Villafranca in Lunigiana"],
    ["name" => "Lois Rosario", "email" => "mauris.rhoncus@elit.edu", "company" => "Dhuy"],
    ["name" => "John Weaver", "email" => "diam.luctus.lobortis@pedePraesenteu.org", "company" => "Tlaquepaque"],
    ["name" => "Charissa Carroll", "email" => "massa@anteblandit.ca", "company" => "Bottrop"],
    ["name" => "Leilani Lynch", "email" => "cursus@tempusnon.edu", "company" => "Villach"],
    ["name" => "Lois Peters", "email" => "enim.Etiam@dignissimpharetraNam.net", "company" => "Vico nel Lazio"],
    ["name" => "Leila Hanson", "email" => "Nulla.semper.tellus@Aliquam.co.uk", "company" => "Landenne"],
    ["name" => "Abbot Simmons", "email" => "hendrerit.neque.In@egestas.com", "company" => "Valda"],
    ["name" => "Merritt Nicholson", "email" => "ipsum@ipsumleo.ca", "company" => "Brandon"],
    ["name" => "Calvin Singleton", "email" => "libero.lacus@Integer.co.uk", "company" => "Wha Ti"],
    ["name" => "Justin Cochran", "email" => "nec@nullaCraseu.co.uk", "company" => "Spinoso"],
    ["name" => "Fletcher Carr", "email" => "congue.elit@aliquetliberoInteger.org", "company" => "Évreux"],
    ["name" => "Timothy Boone", "email" => "Aliquam.nec.enim@est.edu", "company" => "Finspång"],
    ["name" => "Jacqueline Howell", "email" => "mus@laciniaorciconsectetuer.org", "company" => "Warburg"],
    ["name" => "Ulysses Henry", "email" => "egestas@justoeuarcu.co.uk", "company" => "Freux"],
    ["name" => "Tanisha Fisher", "email" => "cursus.purus@maurissapiencursus.co.uk", "company" => "Roio del Sangro"],
    ["name" => "Carlos Collier", "email" => "ut.sem.Nulla@dolorsit.com", "company" => "Dolgellau"],
    ["name" => "Naida Velasquez", "email" => "amet.ultricies.sem@iaculisquis.edu", "company" => "Springfield"],
    ["name" => "Jayme Ferrell", "email" => "urna.Ut@maurissitamet.com", "company" => "Montrose"],
    ["name" => "Calista Crane", "email" => "malesuada.augue.ut@semegestasblandit.com", "company" => "Patna"],
    ["name" => "Alma Herrera", "email" => "ut@Cras.net", "company" => "Veraval"],
    ["name" => "Dora Harrington", "email" => "tincidunt.dui.augue@sit.co.uk", "company" => "Mol"],
    ["name" => "Ebony Perry", "email" => "felis@arcu.edu", "company" => "Brechin"],
    ["name" => "Marsden Gentry", "email" => "ipsum.porta@rhoncus.edu", "company" => "Neyveli"],
    ["name" => "Lee Melton", "email" => "ac@justo.net", "company" => "Bendigo"],
    ["name" => "Zelda Golden", "email" => "imperdiet.non@adipiscing.com", "company" => "Vanderhoof"],
    ["name" => "Magee Harris", "email" => "rutrum.magna@facilisisvitaeorci.org", "company" => "Uppingham. Cottesmore"],
    ["name" => "Ulla Singleton", "email" => "auctor.nunc.nulla@Praesent.co.uk", "company" => "Long Eaton"],
    ["name" => "Lawrence Dotson", "email" => "at.egestas@nec.org", "company" => "Ernage"],
    ["name" => "Carl Gonzales", "email" => "Aenean@mus.edu", "company" => "Archennes"],
    ["name" => "Maxwell Clay", "email" => "convallis.in.cursus@dignissimpharetra.co.uk", "company" => "Sint-Agatha-Berchem"],
    ["name" => "Benjamin Lucas", "email" => "in.faucibus@feugiat.edu", "company" => "Lincoln"],
    ["name" => "Angela Ellison", "email" => "nunc.nulla.vulputate@consectetueradipiscingelit.org", "company" => "Collinas"],
    ["name" => "Ethan Garrett", "email" => "est.vitae.sodales@urnaconvallis.co.uk", "company" => "Purmerend"],
    ["name" => "Callie Gay", "email" => "neque.vitae@vel.net", "company" => "Blue Mountains"],
    ["name" => "Kylan Kerr", "email" => "sagittis@Vestibulumante.co.uk", "company" => "Grasse"],
    ["name" => "Beau Workman", "email" => "in@eratVivamus.com", "company" => "Doel"],
    ["name" => "Freya Richards", "email" => "amet.metus@tinciduntpedeac.org", "company" => "Blevio"],
    ["name" => "Karly Poole", "email" => "pede.Suspendisse@Aeneaneget.edu", "company" => "Kiel"],
    ["name" => "Marvin Elliott", "email" => "consequat.enim.diam@Aliquamadipiscing.ca", "company" => "Lampernisse"],
    ["name" => "Lyle Mosley", "email" => "suscipit.nonummy.Fusce@disparturientmontes.edu", "company" => "Jaboatão dos Guararapes"],
    ["name" => "Nomlanga Bright", "email" => "leo@Fuscealiquam.ca", "company" => "Krasnogorsk"],
    ["name" => "Quin Ramirez", "email" => "accumsan@dis.edu", "company" => "Lissewege"],
    ["name" => "Thaddeus Bryan", "email" => "elit.fermentum.risus@tristique.edu", "company" => "Campos dos Goytacazes"],
    ["name" => "Zia Conley", "email" => "Proin@idnunc.ca", "company" => "Wilmont"],
    ["name" => "Fiona Livingston", "email" => "Aliquam.tincidunt@nuncinterdum.co.uk", "company" => "Vöcklabruck"],
    ["name" => "Martha Serrano", "email" => "neque@porttitorinterdumSed.co.uk", "company" => "Zamość"],
    ["name" => "Colby Noble", "email" => "a.neque@Nuncuterat.ca", "company" => "Enkhuizen"],
    ["name" => "Alfonso Mclaughlin", "email" => "porttitor.eros.nec@sociisnatoquepenatibus.com", "company" => "Woutersbrakel"],
    ["name" => "Minerva Watson", "email" => "luctus@at.co.uk", "company" => "Mglin"],
    ["name" => "Jennifer Russell", "email" => "tincidunt.nunc.ac@dictumsapien.ca", "company" => "North Las Vegas"],
    ["name" => "Yael Campbell", "email" => "nulla.In.tincidunt@malesuadaid.co.uk", "company" => "Foligno"],
    ["name" => "Amir Kemp", "email" => "dictum@Nuncullamcorper.net", "company" => "Leersum"],
    ["name" => "Madaline Compton", "email" => "ante@elementumdui.edu", "company" => "St. John's"],
    ["name" => "Len Hale", "email" => "velit@necanteblandit.org", "company" => "Paisley"],
    ["name" => "Aladdin Chen", "email" => "Proin.mi.Aliquam@sedsapienNunc.org", "company" => "Gorakhpur"],
    ["name" => "Mariko Justice", "email" => "tempor.diam.dictum@estconguea.co.uk", "company" => "Colombes"],
    ["name" => "Blythe Stone", "email" => "mauris@elitpretiumet.edu", "company" => "Tiel"],
    ["name" => "Eagan Rosales", "email" => "netus@lobortis.org", "company" => "Orhangazi"],
    ["name" => "Hadley Whitney", "email" => "dictum.placerat.augue@Pellentesquehabitant.net", "company" => "Falkensee"],
    ["name" => "Mollie Knight", "email" => "Vivamus.molestie.dapibus@eratEtiamvestibulum.org", "company" => "Guben"],
    ["name" => "Yetta Blake", "email" => "odio.semper@risusNullaeget.com", "company" => "Kerikeri"],
    ["name" => "Aurelia Cannon", "email" => "dapibus.ligula@lobortistellus.ca", "company" => "Naperville"],
    ["name" => "Scott Neal", "email" => "dictum.Proin.eget@eget.com", "company" => "Enna"],
    ["name" => "Zeus Knight", "email" => "commodo.ipsum.Suspendisse@euismodest.net", "company" => "Weiterstadt"],
    ["name" => "Kylee Knox", "email" => "interdum@velitegestas.com", "company" => "Recco"],
    ["name" => "Xanthus Chaney", "email" => "pharetra.Nam@imperdietullamcorper.ca", "company" => "Radicofani"],
    ["name" => "Tyrone Olson", "email" => "varius@Nullamnisl.edu", "company" => "Montelupo Fiorentino"],
    ["name" => "Dawn Ratliff", "email" => "gravida.molestie.arcu@liberoestcongue.ca", "company" => "Moerzeke"],
    ["name" => "Alan Jordan", "email" => "sed@ametdapibus.com", "company" => "Sint-Denijs-Westrem"],
    ["name" => "Reed Henderson", "email" => "ornare.egestas.ligula@eleifendvitaeerat.net", "company" => "Villafranca in Lunigiana"],
    ["name" => "Courtney Anderson", "email" => "ornare.lectus@primisinfaucibus.net", "company" => "Morpeth"],
    ["name" => "Rama Hinton", "email" => "mi.enim.condimentum@conubianostraper.com", "company" => "Tarzo"],
    ["name" => "Denton Pickett", "email" => "dui.augue.eu@ultricesiaculis.net", "company" => "Elsene"],
    ["name" => "Oren Mccarthy", "email" => "In.scelerisque@Integeraliquamadipiscing.com", "company" => "Ham-sur-Heure"],
    ["name" => "Kevin Chen", "email" => "pede.Suspendisse@Suspendisse.net", "company" => "Mezzana"],
    ["name" => "Amos Robinson", "email" => "Curabitur.ut@egettincidunt.ca", "company" => "Newport"],
    ["name" => "Quentin Colon", "email" => "eu.erat.semper@ipsumporta.ca", "company" => "Kayseri"],
    ["name" => "Cathleen Carroll", "email" => "Suspendisse@Suspendisseeleifend.org", "company" => "Pitt Meadows"],
    ["name" => "Donovan Massey", "email" => "tempus.risus@eget.ca", "company" => "Goderich"],
    ["name" => "Colette Yang", "email" => "accumsan.laoreet@quam.co.uk", "company" => "Fochabers"],
    ["name" => "Whitney Shaffer", "email" => "nascetur@ultricesVivamus.net", "company" => "Nîmes"],
    ["name" => "Cameron Baker", "email" => "vitae@felisorciadipiscing.net", "company" => "Melipilla"],
    ["name" => "Hashim Mcclain", "email" => "Praesent@tellusPhaselluselit.com", "company" => "Pichidegua"],
    ["name" => "Veronica Velasquez", "email" => "Nullam@urnaNullam.edu", "company" => "Sivry"],
    ["name" => "Taylor Griffin", "email" => "vitae.risus@utpharetrased.com", "company" => "Sant'Egidio del Monte Albino"],
    ["name" => "Yetta Cook", "email" => "ipsum@loremvehiculaet.net", "company" => "Cranbrook"],
    ["name" => "Cassandra Curtis", "email" => "pharetra.felis@placeratCrasdictum.org", "company" => "Cobquecura"],
    ["name" => "Adena Avila", "email" => "morbi.tristique.senectus@eratvitaerisus.co.uk", "company" => "Afsnee"],
    ["name" => "Frances Mcneil", "email" => "cursus.non.egestas@arcu.net", "company" => "Beaconsfield"],
    ["name" => "Beau Quinn", "email" => "a@augueeu.co.uk", "company" => "Dampremy"],
    ["name" => "Montana Rivera", "email" => "arcu.vel.quam@necleoMorbi.com", "company" => "Raipur"],
    ["name" => "Alisa Allison", "email" => "massa.Integer@cursuseteros.com", "company" => "Regina"],
    ["name" => "Vernon Spencer", "email" => "sem.consequat@sed.com", "company" => "Richmond"],
    ["name" => "Ivan Oliver", "email" => "nunc.ullamcorper@Pellentesquetincidunttempus.co.uk", "company" => "Ełk"],
    ["name" => "Katell Galloway", "email" => "Pellentesque.ultricies.dignissim@iaculisaliquetdiam.co.uk", "company" => "Merseburg"],
    ["name" => "Hall White", "email" => "Integer.in@Integersem.net", "company" => "Anchorage"],
    ["name" => "Ariana Raymond", "email" => "nunc@nonummyac.org", "company" => "Yangju"],
    ["name" => "Ella Haley", "email" => "ante.Nunc.mauris@ultriciesornareelit.com", "company" => "Rigolet"],
    ["name" => "Hillary Herman", "email" => "a@Sed.ca", "company" => "Couthuin"],
    ["name" => "Yuri Rivers", "email" => "erat.Vivamus@Fusce.edu", "company" => "Blehen"],
    ["name" => "Lacey Glass", "email" => "sit.amet.risus@disparturientmontes.edu", "company" => "Vizianagaram"],
    ["name" => "Norman Harvey", "email" => "cursus.Nunc@natoquepenatibuset.net", "company" => "Armungia"],
    ["name" => "Noble Bush", "email" => "massa.rutrum.magna@orcitinciduntadipiscing.ca", "company" => "Cisterna di Latina"],
    ["name" => "Akeem Hanson", "email" => "aliquet.libero.Integer@Nam.net", "company" => "Guntakal"],
    ["name" => "August Miles", "email" => "erat@Utsagittislobortis.org", "company" => "Pogliano Milanese"],
    ["name" => "Isaac Owens", "email" => "lorem.Donec.elementum@blandit.net", "company" => "Long Eaton"],
    ["name" => "Brody Anthony", "email" => "dolor.egestas.rhoncus@tincidunt.edu", "company" => "Lochranza"],
    ["name" => "Yetta Mooney", "email" => "lobortis@aliquet.net", "company" => "Flamierge"],
    ["name" => "Denise Erickson", "email" => "ut@nec.org", "company" => "Langholm"],
    ["name" => "Nina Irwin", "email" => "libero@ornarelibero.com", "company" => "Sant'Angelo Limosano"],
    ["name" => "Kieran Smith", "email" => "pharetra@Donecest.net", "company" => "Vanier"],
    ["name" => "Renee Davidson", "email" => "molestie.tellus.Aenean@Loremipsum.ca", "company" => "Sibi"],
    ["name" => "Jakeem Bradshaw", "email" => "pharetra@utodiovel.net", "company" => "Tsiigehtchic"],
    ["name" => "Yolanda Weaver", "email" => "Suspendisse.sagittis.Nullam@viverra.edu", "company" => "New Plymouth"],
    ["name" => "Vaughan Frank", "email" => "sociis@vehiculaPellentesque.org", "company" => "Manavgat"],
    ["name" => "Victor Baldwin", "email" => "Nullam.lobortis@loremauctor.com", "company" => "Putignano"],
    ["name" => "Kennan Robles", "email" => "orci.luctus.et@idante.org", "company" => "Carluke"],
    ["name" => "Barry Burnett", "email" => "lorem.lorem@sedsem.net", "company" => "Waver"],
    ["name" => "Madonna Macdonald", "email" => "neque.venenatis@et.com", "company" => "Rochester"],
    ["name" => "Jael Mullins", "email" => "dolor.tempus@quisturpisvitae.org", "company" => "Isle-aux-Coudres"],
    ["name" => "Ashton Blair", "email" => "egestas@Praesentinterdum.edu", "company" => "Jelenia Góra"],
    ["name" => "Fredericka Roy", "email" => "consectetuer.adipiscing.elit@nuncullamcorpereu.net", "company" => "Blitar"],
    ["name" => "Selma Carver", "email" => "tellus.lorem@urnaVivamus.ca", "company" => "Soacha"],
    ["name" => "Alisa Barton", "email" => "a.ultricies.adipiscing@odiovelest.com", "company" => "Ferness"],
    ["name" => "Adele Mckay", "email" => "eu@arcuiaculisenim.org", "company" => "Lewiston"],
    ["name" => "Robert Peck", "email" => "diam.lorem.auctor@velfaucibus.com", "company" => "San Francisco"],
    ["name" => "Brielle Flowers", "email" => "molestie.sodales@vulputatelacusCras.co.uk", "company" => "Avadi"],
    ["name" => "Claudia Logan", "email" => "taciti.sociosqu.ad@lobortisnisinibh.net", "company" => "Steenokkerzeel"],
    ["name" => "Tarik Henderson", "email" => "non@lobortisquispede.net", "company" => "Würzburg"],
    ["name" => "Janna Dunn", "email" => "leo@risusNulla.co.uk", "company" => "Mathura"],
    ["name" => "Jolie Payne", "email" => "turpis@Donecsollicitudin.ca", "company" => "Bokaro Steel City"],
    ["name" => "Chantale Sanford", "email" => "morbi.tristique.senectus@euaccumsansed.edu", "company" => "Stamford"],
    ["name" => "Melissa Dudley", "email" => "augue.scelerisque.mollis@elit.edu", "company" => "Falun"],
    ["name" => "Nina Cole", "email" => "purus.Duis.elementum@etarcu.edu", "company" => "Crecchio"],
    ["name" => "Ora Walton", "email" => "dui@egestas.ca", "company" => "Kotamobagu"],
    ["name" => "Hollee Blackburn", "email" => "Fusce.fermentum.fermentum@sed.org", "company" => "Zutphen"],
    ["name" => "Cameron Parks", "email" => "hymenaeos.Mauris.ut@arcu.net", "company" => "Palmerston North"],
    ["name" => "Beck Fitzpatrick", "email" => "aliquet@augue.net", "company" => "Salzwedel"],
    ["name" => "Ulric Dennis", "email" => "tristique@Nullamvitae.ca", "company" => "Fort Smith"],
    ["name" => "Jamal Rosario", "email" => "vitae@sagittis.ca", "company" => "Bonnyville"],
    ["name" => "Ferdinand Vang", "email" => "sem@DuisgravidaPraesent.com", "company" => "Wijshagen"],
    ["name" => "Brooke Thomas", "email" => "Lorem@vulputatemauris.ca", "company" => "Perugia"],
    ["name" => "Scott Rodriquez", "email" => "lacus.Cras@ultricesiaculis.co.uk", "company" => "Montemignaio"],
    ["name" => "Halla Gonzalez", "email" => "nulla.ante.iaculis@posuerecubiliaCurae.edu", "company" => "Lodelinsart"],
    ["name" => "Jarrod Jefferson", "email" => "neque.sed.sem@egetmetusIn.ca", "company" => "Łódź"],
    ["name" => "Colette Cannon", "email" => "tortor@fermentum.co.uk", "company" => "Wiekevorst"],
    ["name" => "Tamekah Espinoza", "email" => "faucibus@duisemperet.org", "company" => "Louisville"],
    ["name" => "Ivan Holder", "email" => "facilisis.eget@gravida.com", "company" => "Villa Agnedo"],
    ["name" => "William Christensen", "email" => "primis.in.faucibus@id.org", "company" => "Luino"],
    ["name" => "Katell Cole", "email" => "Integer.urna@nibhlaciniaorci.com", "company" => "Gimpo"],
    ["name" => "Chantale Macdonald", "email" => "Aenean.massa.Integer@liberoProinsed.com", "company" => "Virginia Beach"],
    ["name" => "Rahim Paul", "email" => "Quisque.porttitor@tellussem.org", "company" => "Bekasi"],
    ["name" => "Ulla Ruiz", "email" => "libero.Morbi@acturpis.org", "company" => "Topeka"],
    ["name" => "Shannon Price", "email" => "sapien.Nunc@a.ca", "company" => "Virginal-Samme"],
    ["name" => "Taylor Smith", "email" => "orci.Donec.nibh@molestie.co.uk", "company" => "Aurora"],
    ["name" => "Derek Garrett", "email" => "sit.amet.luctus@loremDonec.net", "company" => "Saint-Honor�"],
    ["name" => "Melissa Hurley", "email" => "sodales@tellusid.org", "company" => "Calle Larga"],
    ["name" => "Ronan Leon", "email" => "sociis.natoque.penatibus@arcuiaculisenim.co.uk", "company" => "Rhyl"],
    ["name" => "Lionel Mcknight", "email" => "non.lacinia@aliquet.edu", "company" => "Roosbeek"],
    ["name" => "Michael Finch", "email" => "quam.dignissim@atiaculis.edu", "company" => "Waitara"],
    ["name" => "Jason Lowery", "email" => "Phasellus.at.augue@Nulladignissim.edu", "company" => "Neudörfl"],
    ["name" => "Charissa Garcia", "email" => "eu.metus@volutpat.edu", "company" => "Montemignaio"],
    ["name" => "Blaze Rowland", "email" => "dui@enimdiam.co.uk", "company" => "Omsk"],
    ["name" => "Jared Cobb", "email" => "Sed.molestie.Sed@risus.org", "company" => "Malegaon"],
    ["name" => "Darius Bray", "email" => "leo.in.lobortis@velvulputate.net", "company" => "Ashoknagar-Kalyangarh"],
    ["name" => "Giacomo Odom", "email" => "ut.lacus@Morbi.org", "company" => "Penrith"],
    ["name" => "Beatrice Herman", "email" => "Maecenas@mollisnoncursus.edu", "company" => "Bulzi"],
    ["name" => "Kylynn Curtis", "email" => "Fusce@eratnonummyultricies.ca", "company" => "Nil-Saint-Vincent-Saint-Martin"],
    ["name" => "Berk Woodward", "email" => "lacinia.at@metusurnaconvallis.net", "company" => "Guardia Sanframondi"],
    ["name" => "Halee Terry", "email" => "nibh@Donec.net", "company" => "Kielce"],
    ["name" => "Cassandra Hopper", "email" => "sit.amet.massa@augue.ca", "company" => "Quellón"],
    ["name" => "Ila Huff", "email" => "sapien@turpisegestasFusce.net", "company" => "Genk"],
    ["name" => "Eleanor Burch", "email" => "lobortis@diam.com", "company" => "Sabanalarga"],
    ["name" => "Quinn Hess", "email" => "tristique.senectus@egestasa.org", "company" => "Icheon"],
    ["name" => "Sean Delacruz", "email" => "Cum.sociis.natoque@utsemNulla.ca", "company" => "Grosseto"],
    ["name" => "Anjolie Faulkner", "email" => "pharetra.ut@euismodmauris.net", "company" => "Gaithersburg"],
    ["name" => "Hanna Soto", "email" => "mi.Duis@Vestibulum.co.uk", "company" => "Dover"],
    ["name" => "Abbot Roberson", "email" => "risus.Nulla.eget@scelerisque.com", "company" => "Springdale"],
    ["name" => "Yoshio Ray", "email" => "adipiscing.lacus@feugiat.co.uk", "company" => "Pogliano Milanese"],
    ["name" => "Jamal Mercado", "email" => "consectetuer.cursus.et@nonsapienmolestie.co.uk", "company" => "Ladispoli"],
    ["name" => "Iliana Taylor", "email" => "vel.faucibus.id@Integer.edu", "company" => "Rocourt"],
    ["name" => "Belle Webster", "email" => "Fusce.dolor.quam@Curabitursedtortor.ca", "company" => "Rutigliano"],
    ["name" => "Cathleen Mckee", "email" => "urna.nec.luctus@rutrummagnaCras.net", "company" => "Quinchao"],
];

$res = array_filter($data, function ($k, $v) {
    global $filter;
    //error_log("filter $filter");
    //error_log("v $v");
    $key = strtolower($k['name'] . ' ' . $k['email'] . $k['company']);
    if (strpos($key, $filter) !== false) {
        return true;
    }
    return false;
}, ARRAY_FILTER_USE_BOTH);

/**
 * Returning results.
 * Let's format depending on the format parameter: 'plain' or 'object' (default)
 */
if ($format === 'plain') {
    $plainRes = [];
    foreach ($res as $key => $value) {
        $plainRes[] = "{$value['name']} ({$value['email']}) de {$value['company']}";
    }
    echo json_encode($plainRes);
} else {
    echo json_encode($res);
}

